[package]
name = "rusty_rpc"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
nom = "7.1.1"
proc-macro2 = "1.0.39"
quote = "1.0.18"
syn = { version = "1.0.95", features = ["full"] }
